name: build and test
on:
  push:
    branches:
      - master

jobs:
  build:
    name: build and test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
    - run: npm install
    - run: touch node_modules/@jymfony/decorators/index.d.ts # Bug: "error TS2688: Cannot find type definition file for 'decorators'."
    - run: npm test
      env:
        CI: true
    - run: npm run build
