name: Tests
on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node_version:
                    - '12'
                    - '14'
                    - '16'
                    - '18'
                    - '19'

        name: Node.JS ${{ matrix.node_version }}
        steps:
            - uses: actions/checkout@v3

            - name: Setup Node.JS ${{ matrix.node_version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node_version }}

            - run: npm install
            - run: npm test
              if: matrix.node_version != '14'
            - run: npm run-script coverage
              if: matrix.node_version == '14'

            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v3
              with:
                  file: ./coverage/clover.xml
